---
- hosts: all
  become: true
  tasks:

  - name: update package cache for Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: update package cache for CentOS
    dnf:
      name: epel-release
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: nagios
  become: true
  roles:
    - nagios
